//*****************************************************************************
//
// Author		: Trotzky Vasily
// Date			: apr 2017
// All rights reserved.

// Redistribution and use in source and binary forms, with or without modification, 
// are permitted provided that the following conditions are met:
// Redistributions of source code must retain the above copyright notice, 
// this list of conditions and the following disclaimer.

// Redistributions in binary form must reproduce the above copyright notice, 
// this list of conditions and the following disclaimer in the documentation and/or 
// other materials provided with the distribution.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
// IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
// BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY 
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, 
// EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//*****************************************************************************
#ifndef IOCONF_DEFAULTCONF_H_
#define IOCONF_DEFAULTCONF_H_

/*
* Use YES or NO!
* DO NOT DELETE! Just YES or NO! This is important!
* If this MCU model has pin 0 on port A then you should
* #define IOCONF_MCU_HAS_Pa0  YES
* else
* #define IOCONF_MCU_HAS_Pa0  NO
*/

/*
This is default config
Please _say YES_ to ALL POSSIBLE ports and pins!
*/

//Port A
#define IOCONF_MCU_HAS_Pa0   YES
#define IOCONF_MCU_HAS_Pa1   YES
#define IOCONF_MCU_HAS_Pa2   YES
#define IOCONF_MCU_HAS_Pa3   YES
#define IOCONF_MCU_HAS_Pa4   YES
#define IOCONF_MCU_HAS_Pa5   YES
#define IOCONF_MCU_HAS_Pa6   YES
#define IOCONF_MCU_HAS_Pa7   YES
#define IOCONF_MCU_HAS_Pa8   YES
#define IOCONF_MCU_HAS_Pa9   YES
#define IOCONF_MCU_HAS_Pa10  YES
#define IOCONF_MCU_HAS_Pa11  YES
#define IOCONF_MCU_HAS_Pa12  YES
#define IOCONF_MCU_HAS_Pa13  YES
#define IOCONF_MCU_HAS_Pa14  YES
#define IOCONF_MCU_HAS_Pa15  YES
#define IOCONF_MCU_HAS_Pa16  YES
#define IOCONF_MCU_HAS_Pa17  YES
#define IOCONF_MCU_HAS_Pa18  YES
#define IOCONF_MCU_HAS_Pa19  YES
#define IOCONF_MCU_HAS_Pa20  YES
#define IOCONF_MCU_HAS_Pa21  YES
#define IOCONF_MCU_HAS_Pa22  YES
#define IOCONF_MCU_HAS_Pa23  YES
#define IOCONF_MCU_HAS_Pa24  YES
#define IOCONF_MCU_HAS_Pa25  YES
#define IOCONF_MCU_HAS_Pa26  YES
#define IOCONF_MCU_HAS_Pa27  YES
#define IOCONF_MCU_HAS_Pa28  YES
#define IOCONF_MCU_HAS_Pa29  YES
#define IOCONF_MCU_HAS_Pa30  YES
#define IOCONF_MCU_HAS_Pa31  YES

//Port B
#define IOCONF_MCU_HAS_Pb0   YES
#define IOCONF_MCU_HAS_Pb1   YES
#define IOCONF_MCU_HAS_Pb2   YES
#define IOCONF_MCU_HAS_Pb3   YES
#define IOCONF_MCU_HAS_Pb4   YES
#define IOCONF_MCU_HAS_Pb5   YES
#define IOCONF_MCU_HAS_Pb6   YES
#define IOCONF_MCU_HAS_Pb7   YES
#define IOCONF_MCU_HAS_Pb8   YES
#define IOCONF_MCU_HAS_Pb9   YES
#define IOCONF_MCU_HAS_Pb10  YES
#define IOCONF_MCU_HAS_Pb11  YES
#define IOCONF_MCU_HAS_Pb12  YES
#define IOCONF_MCU_HAS_Pb13  YES
#define IOCONF_MCU_HAS_Pb14  YES
#define IOCONF_MCU_HAS_Pb15  YES
#define IOCONF_MCU_HAS_Pb16  YES
#define IOCONF_MCU_HAS_Pb17  YES
#define IOCONF_MCU_HAS_Pb18  YES
#define IOCONF_MCU_HAS_Pb19  YES
#define IOCONF_MCU_HAS_Pb20  YES
#define IOCONF_MCU_HAS_Pb21  YES
#define IOCONF_MCU_HAS_Pb22  YES
#define IOCONF_MCU_HAS_Pb23  YES
#define IOCONF_MCU_HAS_Pb24  YES
#define IOCONF_MCU_HAS_Pb25  YES
#define IOCONF_MCU_HAS_Pb26  YES
#define IOCONF_MCU_HAS_Pb27  YES
#define IOCONF_MCU_HAS_Pb28  YES
#define IOCONF_MCU_HAS_Pb29  YES
#define IOCONF_MCU_HAS_Pb30  YES
#define IOCONF_MCU_HAS_Pb31  YES

//Port C
#define IOCONF_MCU_HAS_Pc0   YES
#define IOCONF_MCU_HAS_Pc1   YES
#define IOCONF_MCU_HAS_Pc2   YES
#define IOCONF_MCU_HAS_Pc3   YES
#define IOCONF_MCU_HAS_Pc4   YES
#define IOCONF_MCU_HAS_Pc5   YES
#define IOCONF_MCU_HAS_Pc6   YES
#define IOCONF_MCU_HAS_Pc7   YES
#define IOCONF_MCU_HAS_Pc8   YES
#define IOCONF_MCU_HAS_Pc9   YES
#define IOCONF_MCU_HAS_Pc10  YES
#define IOCONF_MCU_HAS_Pc11  YES
#define IOCONF_MCU_HAS_Pc12  YES
#define IOCONF_MCU_HAS_Pc13  YES
#define IOCONF_MCU_HAS_Pc14  YES
#define IOCONF_MCU_HAS_Pc15  YES
#define IOCONF_MCU_HAS_Pc16  YES
#define IOCONF_MCU_HAS_Pc17  YES
#define IOCONF_MCU_HAS_Pc18  YES
#define IOCONF_MCU_HAS_Pc19  YES
#define IOCONF_MCU_HAS_Pc20  YES
#define IOCONF_MCU_HAS_Pc21  YES
#define IOCONF_MCU_HAS_Pc22  YES
#define IOCONF_MCU_HAS_Pc23  YES
#define IOCONF_MCU_HAS_Pc24  YES
#define IOCONF_MCU_HAS_Pc25  YES
#define IOCONF_MCU_HAS_Pc26  YES
#define IOCONF_MCU_HAS_Pc27  YES
#define IOCONF_MCU_HAS_Pc28  YES
#define IOCONF_MCU_HAS_Pc29  YES
#define IOCONF_MCU_HAS_Pc30  YES
#define IOCONF_MCU_HAS_Pc31  YES

//Port D
#define IOCONF_MCU_HAS_Pd0   YES
#define IOCONF_MCU_HAS_Pd1   YES
#define IOCONF_MCU_HAS_Pd2   YES
#define IOCONF_MCU_HAS_Pd3   YES
#define IOCONF_MCU_HAS_Pd4   YES
#define IOCONF_MCU_HAS_Pd5   YES
#define IOCONF_MCU_HAS_Pd6   YES
#define IOCONF_MCU_HAS_Pd7   YES
#define IOCONF_MCU_HAS_Pd8   YES
#define IOCONF_MCU_HAS_Pd9   YES
#define IOCONF_MCU_HAS_Pd10  YES
#define IOCONF_MCU_HAS_Pd11  YES
#define IOCONF_MCU_HAS_Pd12  YES
#define IOCONF_MCU_HAS_Pd13  YES
#define IOCONF_MCU_HAS_Pd14  YES
#define IOCONF_MCU_HAS_Pd15  YES
#define IOCONF_MCU_HAS_Pd16  YES
#define IOCONF_MCU_HAS_Pd17  YES
#define IOCONF_MCU_HAS_Pd18  YES
#define IOCONF_MCU_HAS_Pd19  YES
#define IOCONF_MCU_HAS_Pd20  YES
#define IOCONF_MCU_HAS_Pd21  YES
#define IOCONF_MCU_HAS_Pd22  YES
#define IOCONF_MCU_HAS_Pd23  YES
#define IOCONF_MCU_HAS_Pd24  YES
#define IOCONF_MCU_HAS_Pd25  YES
#define IOCONF_MCU_HAS_Pd26  YES
#define IOCONF_MCU_HAS_Pd27  YES
#define IOCONF_MCU_HAS_Pd28  YES
#define IOCONF_MCU_HAS_Pd29  YES
#define IOCONF_MCU_HAS_Pd30  YES
#define IOCONF_MCU_HAS_Pd31  YES

//Port E
#define IOCONF_MCU_HAS_Pe0   YES
#define IOCONF_MCU_HAS_Pe1   YES
#define IOCONF_MCU_HAS_Pe2   YES
#define IOCONF_MCU_HAS_Pe3   YES
#define IOCONF_MCU_HAS_Pe4   YES
#define IOCONF_MCU_HAS_Pe5   YES
#define IOCONF_MCU_HAS_Pe6   YES
#define IOCONF_MCU_HAS_Pe7   YES
#define IOCONF_MCU_HAS_Pe8   YES
#define IOCONF_MCU_HAS_Pe9   YES
#define IOCONF_MCU_HAS_Pe10  YES
#define IOCONF_MCU_HAS_Pe11  YES
#define IOCONF_MCU_HAS_Pe12  YES
#define IOCONF_MCU_HAS_Pe13  YES
#define IOCONF_MCU_HAS_Pe14  YES
#define IOCONF_MCU_HAS_Pe15  YES
#define IOCONF_MCU_HAS_Pe16  YES
#define IOCONF_MCU_HAS_Pe17  YES
#define IOCONF_MCU_HAS_Pe18  YES
#define IOCONF_MCU_HAS_Pe19  YES
#define IOCONF_MCU_HAS_Pe20  YES
#define IOCONF_MCU_HAS_Pe21  YES
#define IOCONF_MCU_HAS_Pe22  YES
#define IOCONF_MCU_HAS_Pe23  YES
#define IOCONF_MCU_HAS_Pe24  YES
#define IOCONF_MCU_HAS_Pe25  YES
#define IOCONF_MCU_HAS_Pe26  YES
#define IOCONF_MCU_HAS_Pe27  YES
#define IOCONF_MCU_HAS_Pe28  YES
#define IOCONF_MCU_HAS_Pe29  YES
#define IOCONF_MCU_HAS_Pe30  YES
#define IOCONF_MCU_HAS_Pe31  YES

//Port F
#define IOCONF_MCU_HAS_Pf0   YES
#define IOCONF_MCU_HAS_Pf1   YES
#define IOCONF_MCU_HAS_Pf2   YES
#define IOCONF_MCU_HAS_Pf3   YES
#define IOCONF_MCU_HAS_Pf4   YES
#define IOCONF_MCU_HAS_Pf5   YES
#define IOCONF_MCU_HAS_Pf6   YES
#define IOCONF_MCU_HAS_Pf7   YES
#define IOCONF_MCU_HAS_Pf8   YES
#define IOCONF_MCU_HAS_Pf9   YES
#define IOCONF_MCU_HAS_Pf10  YES
#define IOCONF_MCU_HAS_Pf11  YES
#define IOCONF_MCU_HAS_Pf12  YES
#define IOCONF_MCU_HAS_Pf13  YES
#define IOCONF_MCU_HAS_Pf14  YES
#define IOCONF_MCU_HAS_Pf15  YES
#define IOCONF_MCU_HAS_Pf16  YES
#define IOCONF_MCU_HAS_Pf17  YES
#define IOCONF_MCU_HAS_Pf18  YES
#define IOCONF_MCU_HAS_Pf19  YES
#define IOCONF_MCU_HAS_Pf20  YES
#define IOCONF_MCU_HAS_Pf21  YES
#define IOCONF_MCU_HAS_Pf22  YES
#define IOCONF_MCU_HAS_Pf23  YES
#define IOCONF_MCU_HAS_Pf24  YES
#define IOCONF_MCU_HAS_Pf25  YES
#define IOCONF_MCU_HAS_Pf26  YES
#define IOCONF_MCU_HAS_Pf27  YES
#define IOCONF_MCU_HAS_Pf28  YES
#define IOCONF_MCU_HAS_Pf29  YES
#define IOCONF_MCU_HAS_Pf30  YES
#define IOCONF_MCU_HAS_Pf31  YES

//Port G
#define IOCONF_MCU_HAS_Pg0   YES
#define IOCONF_MCU_HAS_Pg1   YES
#define IOCONF_MCU_HAS_Pg2   YES
#define IOCONF_MCU_HAS_Pg3   YES
#define IOCONF_MCU_HAS_Pg4   YES
#define IOCONF_MCU_HAS_Pg5   YES
#define IOCONF_MCU_HAS_Pg6   YES
#define IOCONF_MCU_HAS_Pg7   YES
#define IOCONF_MCU_HAS_Pg8   YES
#define IOCONF_MCU_HAS_Pg9   YES
#define IOCONF_MCU_HAS_Pg10  YES
#define IOCONF_MCU_HAS_Pg11  YES
#define IOCONF_MCU_HAS_Pg12  YES
#define IOCONF_MCU_HAS_Pg13  YES
#define IOCONF_MCU_HAS_Pg14  YES
#define IOCONF_MCU_HAS_Pg15  YES
#define IOCONF_MCU_HAS_Pg16  YES
#define IOCONF_MCU_HAS_Pg17  YES
#define IOCONF_MCU_HAS_Pg18  YES
#define IOCONF_MCU_HAS_Pg19  YES
#define IOCONF_MCU_HAS_Pg20  YES
#define IOCONF_MCU_HAS_Pg21  YES
#define IOCONF_MCU_HAS_Pg22  YES
#define IOCONF_MCU_HAS_Pg23  YES
#define IOCONF_MCU_HAS_Pg24  YES
#define IOCONF_MCU_HAS_Pg25  YES
#define IOCONF_MCU_HAS_Pg26  YES
#define IOCONF_MCU_HAS_Pg27  YES
#define IOCONF_MCU_HAS_Pg28  YES
#define IOCONF_MCU_HAS_Pg29  YES
#define IOCONF_MCU_HAS_Pg30  YES
#define IOCONF_MCU_HAS_Pg31  YES

//Port H
#define IOCONF_MCU_HAS_Ph0   YES
#define IOCONF_MCU_HAS_Ph1   YES
#define IOCONF_MCU_HAS_Ph2   YES
#define IOCONF_MCU_HAS_Ph3   YES
#define IOCONF_MCU_HAS_Ph4   YES
#define IOCONF_MCU_HAS_Ph5   YES
#define IOCONF_MCU_HAS_Ph6   YES
#define IOCONF_MCU_HAS_Ph7   YES
#define IOCONF_MCU_HAS_Ph8   YES
#define IOCONF_MCU_HAS_Ph9   YES
#define IOCONF_MCU_HAS_Ph10  YES
#define IOCONF_MCU_HAS_Ph11  YES
#define IOCONF_MCU_HAS_Ph12  YES
#define IOCONF_MCU_HAS_Ph13  YES
#define IOCONF_MCU_HAS_Ph14  YES
#define IOCONF_MCU_HAS_Ph15  YES
#define IOCONF_MCU_HAS_Ph16  YES
#define IOCONF_MCU_HAS_Ph17  YES
#define IOCONF_MCU_HAS_Ph18  YES
#define IOCONF_MCU_HAS_Ph19  YES
#define IOCONF_MCU_HAS_Ph20  YES
#define IOCONF_MCU_HAS_Ph21  YES
#define IOCONF_MCU_HAS_Ph22  YES
#define IOCONF_MCU_HAS_Ph23  YES
#define IOCONF_MCU_HAS_Ph24  YES
#define IOCONF_MCU_HAS_Ph25  YES
#define IOCONF_MCU_HAS_Ph26  YES
#define IOCONF_MCU_HAS_Ph27  YES
#define IOCONF_MCU_HAS_Ph28  YES
#define IOCONF_MCU_HAS_Ph29  YES
#define IOCONF_MCU_HAS_Ph30  YES
#define IOCONF_MCU_HAS_Ph31  YES

//Port I
#define IOCONF_MCU_HAS_Pi0   YES
#define IOCONF_MCU_HAS_Pi1   YES
#define IOCONF_MCU_HAS_Pi2   YES
#define IOCONF_MCU_HAS_Pi3   YES
#define IOCONF_MCU_HAS_Pi4   YES
#define IOCONF_MCU_HAS_Pi5   YES
#define IOCONF_MCU_HAS_Pi6   YES
#define IOCONF_MCU_HAS_Pi7   YES
#define IOCONF_MCU_HAS_Pi8   YES
#define IOCONF_MCU_HAS_Pi9   YES
#define IOCONF_MCU_HAS_Pi10  YES
#define IOCONF_MCU_HAS_Pi11  YES
#define IOCONF_MCU_HAS_Pi12  YES
#define IOCONF_MCU_HAS_Pi13  YES
#define IOCONF_MCU_HAS_Pi14  YES
#define IOCONF_MCU_HAS_Pi15  YES
#define IOCONF_MCU_HAS_Pi16  YES
#define IOCONF_MCU_HAS_Pi17  YES
#define IOCONF_MCU_HAS_Pi18  YES
#define IOCONF_MCU_HAS_Pi19  YES
#define IOCONF_MCU_HAS_Pi20  YES
#define IOCONF_MCU_HAS_Pi21  YES
#define IOCONF_MCU_HAS_Pi22  YES
#define IOCONF_MCU_HAS_Pi23  YES
#define IOCONF_MCU_HAS_Pi24  YES
#define IOCONF_MCU_HAS_Pi25  YES
#define IOCONF_MCU_HAS_Pi26  YES
#define IOCONF_MCU_HAS_Pi27  YES
#define IOCONF_MCU_HAS_Pi28  YES
#define IOCONF_MCU_HAS_Pi29  YES
#define IOCONF_MCU_HAS_Pi30  YES
#define IOCONF_MCU_HAS_Pi31  YES

//Port J
#define IOCONF_MCU_HAS_Pj0   YES
#define IOCONF_MCU_HAS_Pj1   YES
#define IOCONF_MCU_HAS_Pj2   YES
#define IOCONF_MCU_HAS_Pj3   YES
#define IOCONF_MCU_HAS_Pj4   YES
#define IOCONF_MCU_HAS_Pj5   YES
#define IOCONF_MCU_HAS_Pj6   YES
#define IOCONF_MCU_HAS_Pj7   YES
#define IOCONF_MCU_HAS_Pj8   YES
#define IOCONF_MCU_HAS_Pj9   YES
#define IOCONF_MCU_HAS_Pj10  YES
#define IOCONF_MCU_HAS_Pj11  YES
#define IOCONF_MCU_HAS_Pj12  YES
#define IOCONF_MCU_HAS_Pj13  YES
#define IOCONF_MCU_HAS_Pj14  YES
#define IOCONF_MCU_HAS_Pj15  YES
#define IOCONF_MCU_HAS_Pj16  YES
#define IOCONF_MCU_HAS_Pj17  YES
#define IOCONF_MCU_HAS_Pj18  YES
#define IOCONF_MCU_HAS_Pj19  YES
#define IOCONF_MCU_HAS_Pj20  YES
#define IOCONF_MCU_HAS_Pj21  YES
#define IOCONF_MCU_HAS_Pj22  YES
#define IOCONF_MCU_HAS_Pj23  YES
#define IOCONF_MCU_HAS_Pj24  YES
#define IOCONF_MCU_HAS_Pj25  YES
#define IOCONF_MCU_HAS_Pj26  YES
#define IOCONF_MCU_HAS_Pj27  YES
#define IOCONF_MCU_HAS_Pj28  YES
#define IOCONF_MCU_HAS_Pj29  YES
#define IOCONF_MCU_HAS_Pj30  YES
#define IOCONF_MCU_HAS_Pj31  YES

//Port K
#define IOCONF_MCU_HAS_Pk0   YES
#define IOCONF_MCU_HAS_Pk1   YES
#define IOCONF_MCU_HAS_Pk2   YES
#define IOCONF_MCU_HAS_Pk3   YES
#define IOCONF_MCU_HAS_Pk4   YES
#define IOCONF_MCU_HAS_Pk5   YES
#define IOCONF_MCU_HAS_Pk6   YES
#define IOCONF_MCU_HAS_Pk7   YES
#define IOCONF_MCU_HAS_Pk8   YES
#define IOCONF_MCU_HAS_Pk9   YES
#define IOCONF_MCU_HAS_Pk10  YES
#define IOCONF_MCU_HAS_Pk11  YES
#define IOCONF_MCU_HAS_Pk12  YES
#define IOCONF_MCU_HAS_Pk13  YES
#define IOCONF_MCU_HAS_Pk14  YES
#define IOCONF_MCU_HAS_Pk15  YES
#define IOCONF_MCU_HAS_Pk16  YES
#define IOCONF_MCU_HAS_Pk17  YES
#define IOCONF_MCU_HAS_Pk18  YES
#define IOCONF_MCU_HAS_Pk19  YES
#define IOCONF_MCU_HAS_Pk20  YES
#define IOCONF_MCU_HAS_Pk21  YES
#define IOCONF_MCU_HAS_Pk22  YES
#define IOCONF_MCU_HAS_Pk23  YES
#define IOCONF_MCU_HAS_Pk24  YES
#define IOCONF_MCU_HAS_Pk25  YES
#define IOCONF_MCU_HAS_Pk26  YES
#define IOCONF_MCU_HAS_Pk27  YES
#define IOCONF_MCU_HAS_Pk28  YES
#define IOCONF_MCU_HAS_Pk29  YES
#define IOCONF_MCU_HAS_Pk30  YES
#define IOCONF_MCU_HAS_Pk31  YES

//Port Q
#define IOCONF_MCU_HAS_Pq0   YES
#define IOCONF_MCU_HAS_Pq1   YES
#define IOCONF_MCU_HAS_Pq2   YES
#define IOCONF_MCU_HAS_Pq3   YES
#define IOCONF_MCU_HAS_Pq4   YES
#define IOCONF_MCU_HAS_Pq5   YES
#define IOCONF_MCU_HAS_Pq6   YES
#define IOCONF_MCU_HAS_Pq7   YES
#define IOCONF_MCU_HAS_Pq8   YES
#define IOCONF_MCU_HAS_Pq9   YES
#define IOCONF_MCU_HAS_Pq10  YES
#define IOCONF_MCU_HAS_Pq11  YES
#define IOCONF_MCU_HAS_Pq12  YES
#define IOCONF_MCU_HAS_Pq13  YES
#define IOCONF_MCU_HAS_Pq14  YES
#define IOCONF_MCU_HAS_Pq15  YES
#define IOCONF_MCU_HAS_Pq16  YES
#define IOCONF_MCU_HAS_Pq17  YES
#define IOCONF_MCU_HAS_Pq18  YES
#define IOCONF_MCU_HAS_Pq19  YES
#define IOCONF_MCU_HAS_Pq20  YES
#define IOCONF_MCU_HAS_Pq21  YES
#define IOCONF_MCU_HAS_Pq22  YES
#define IOCONF_MCU_HAS_Pq23  YES
#define IOCONF_MCU_HAS_Pq24  YES
#define IOCONF_MCU_HAS_Pq25  YES
#define IOCONF_MCU_HAS_Pq26  YES
#define IOCONF_MCU_HAS_Pq27  YES
#define IOCONF_MCU_HAS_Pq28  YES
#define IOCONF_MCU_HAS_Pq29  YES
#define IOCONF_MCU_HAS_Pq30  YES
#define IOCONF_MCU_HAS_Pq31  YES

//Port R
#define IOCONF_MCU_HAS_Pr0   YES
#define IOCONF_MCU_HAS_Pr1   YES
#define IOCONF_MCU_HAS_Pr2   YES
#define IOCONF_MCU_HAS_Pr3   YES
#define IOCONF_MCU_HAS_Pr4   YES
#define IOCONF_MCU_HAS_Pr5   YES
#define IOCONF_MCU_HAS_Pr6   YES
#define IOCONF_MCU_HAS_Pr7   YES
#define IOCONF_MCU_HAS_Pr8   YES
#define IOCONF_MCU_HAS_Pr9   YES
#define IOCONF_MCU_HAS_Pr10  YES
#define IOCONF_MCU_HAS_Pr11  YES
#define IOCONF_MCU_HAS_Pr12  YES
#define IOCONF_MCU_HAS_Pr13  YES
#define IOCONF_MCU_HAS_Pr14  YES
#define IOCONF_MCU_HAS_Pr15  YES
#define IOCONF_MCU_HAS_Pr16  YES
#define IOCONF_MCU_HAS_Pr17  YES
#define IOCONF_MCU_HAS_Pr18  YES
#define IOCONF_MCU_HAS_Pr19  YES
#define IOCONF_MCU_HAS_Pr20  YES
#define IOCONF_MCU_HAS_Pr21  YES
#define IOCONF_MCU_HAS_Pr22  YES
#define IOCONF_MCU_HAS_Pr23  YES
#define IOCONF_MCU_HAS_Pr24  YES
#define IOCONF_MCU_HAS_Pr25  YES
#define IOCONF_MCU_HAS_Pr26  YES
#define IOCONF_MCU_HAS_Pr27  YES
#define IOCONF_MCU_HAS_Pr28  YES
#define IOCONF_MCU_HAS_Pr29  YES
#define IOCONF_MCU_HAS_Pr30  YES
#define IOCONF_MCU_HAS_Pr31  YES

#endif //IOCONF_DEFAULTCONF_H_