/*
Modified by: tabr, 2012-2013
*/
#define RFM22B_REGISTER_00_DEVICE_TYPE                                    0x00//00111
#define RFM22B_REGISTER_01_DEVICE_VERSION                                 0x01//06h
#define RFM22B_REGISTER_02_DEVICE_STATUS                                  0x02//-
#define RFM22B_REGISTER_03_INTERRUPT_STATUS_1                             0x03//-
#define RFM22B_REGISTER_04_INTERRUPT_STATUS_2                             0x04//-
#define RFM22B_REGISTER_05_INTERRUPT_ENABLE_1                             0x05//00h
#define RFM22B_REGISTER_06_INTERRUPT_ENABLE_2                             0x06//03h
#define RFM22B_REGISTER_07_OPERATING_FUNCTION_CONTROL_1                   0x07//01h
#define RFM22B_REGISTER_08_OPERATING_FUNCTION_CONTROL_2                   0x08//00h
#define RFM22B_REGISTER_09_CRYSTAL_OSCILLATOR_LOAD_CAPACITANCE            0x09//7Fh
#define RFM22B_REGISTER_0A_MICROCONTROLLER_OUTPUT_CLOCK                   0x0A//06h
#define RFM22B_REGISTER_0B_GPIO_0_CONFIGURATION                           0x0B//00h
#define RFM22B_REGISTER_0C_GPIO_1_CONFIGURATION                           0x0C//00h
#define RFM22B_REGISTER_0D_GPIO_2_CONFIGURATION                           0x0D//00h
#define RFM22B_REGISTER_0E_IO_PORT_CONFIGURATION                          0x0E//00h
#define RFM22B_REGISTER_0F_ADC_CONFIGURATION                              0x0F//00h
#define RFM22B_REGISTER_10_ADC_SENSOR_AMPLIFIER_OFFSET                    0x10//00h
#define RFM22B_REGISTER_11_ADC_VALUE                                      0x11//-
#define RFM22B_REGISTER_12_TEMPERATURE_SENSOR_CONTROL                     0x12//20h
#define RFM22B_REGISTER_13_TEMPERATURE_VALUE_OFFSET                       0x13//00h
#define RFM22B_REGISTER_14_WAKEUP_TIMER_PERIOD_1                          0x14//03h
#define RFM22B_REGISTER_15_WAKEUP_TIMER_PERIOD_2                          0x15//00h
#define RFM22B_REGISTER_16_WAKEUP_TIMER_PERIOD_3                          0x16//01h
#define RFM22B_REGISTER_17_WAKEUP_TIMER_VALUE_1                           0x17//-
#define RFM22B_REGISTER_18_WAKEUP_TIMER_VALUE_2                           0x18//-
#define RFM22B_REGISTER_19_LOW_DUTY_CYCLE_MODE_DURATION                   0x19//00h
#define RFM22B_REGISTER_1A_LOW_BATTERY_DETECTOR_THRESHOLD                 0x1A//14h
#define RFM22B_REGISTER_1B_BATTERY_VOLTAGE_LEVEL                          0x1B//-
#define RFM22B_REGISTER_1C_IF_FILTER_BANDWIDTH                            0x1C//01h
#define RFM22B_REGISTER_1D_AFC_LOOP_GEARSHIFT_OVERRIDE                    0x1D//40h
#define RFM22B_REGISTER_1E_AFC_TIMING_CONTROL                             0x1E//0Ah
#define RFM22B_REGISTER_1F_CLOCK_RECOVERY_GEARSHIFT_OVERRIDE              0x1F//03h
#define RFM22B_REGISTER_20_CLOCK_RECOVERY_OVERSAMPLING_RATIO              0x20//64h
#define RFM22B_REGISTER_21_CLOCK_RECOVERY_OFFSET_2                        0x21//01h
#define RFM22B_REGISTER_22_CLOCK_RECOVERY_OFFSET_1                        0x22//47h
#define RFM22B_REGISTER_23_CLOCK_RECOVERY_OFFSET_0                        0x23//AEh
#define RFM22B_REGISTER_24_CLOCK_RECOVERY_TIMING_LOOP_GAIN_1              0x24//02h
#define RFM22B_REGISTER_25_CLOCK_RECOVERY_TIMING_LOOP_GAIN_0              0x25//8Fh
#define RFM22B_REGISTER_26_RECEIVED_SIGNAL_STRENGTH_INDICATOR             0x26//-
#define RFM22B_REGISTER_26_RSSI                                           0x26//-
#define RFM22B_REGISTER_27_RSSI_THRESHOLD_FOR_CLEAR_CHANNEL_INDICATOR     0x27//1Eh
#define RFM22B_REGISTER_28_ANTENNA_DIVERSITY_REGISTER__1                  0x28//-
#define RFM22B_REGISTER_29_ANTENNA_DIVERSITY_REGISTER__2                  0x29//-
#define RFM22B_REGISTER_2A_AFC_LIMITER                                    0x2A//00h
#define RFM22B_REGISTER_2B_AFC_CORRECTION_READ                            0x2B//00h
#define RFM22B_REGISTER_2C_OOK_COUNTER_VALUE_1                            0x2C//18h
#define RFM22B_REGISTER_2D_OOK_COUNTER_VALUE_2                            0x2D//BCh
#define RFM22B_REGISTER_2E_SLICER_PEAK_HOLD                               0x2E//26h
//#define RFM22B_REGISTER_RESERVED                                        0x2F
#define RFM22B_REGISTER_30_DATA_ACCESS_CONTROL                            0x30//8Dh
#define RFM22B_REGISTER_31_EZMAC_STATUS                                   0x31//-
#define RFM22B_REGISTER_32_HEADER_CONTROL_1                               0x32//0Ch
#define RFM22B_REGISTER_33_HEADER_CONTROL_2                               0x33//22h
#define RFM22B_REGISTER_34_PREAMBLE_LENGTH                                0x34//08h
#define RFM22B_REGISTER_35_PREAMBLE_DETECTION_CONTROL                     0x35//2Ah
#define RFM22B_REGISTER_36_SYNC_WORD_3                                    0x36//2Dh
#define RFM22B_REGISTER_37_SYNC_WORD_2                                    0x37//D4h
#define RFM22B_REGISTER_38_SYNC_WORD_1                                    0x38//00h
#define RFM22B_REGISTER_39_SYNC_WORD_0                                    0x39//00h
#define RFM22B_REGISTER_3A_TRANSMIT_HEADER_3                              0x3A//00h
#define RFM22B_REGISTER_3B_TRANSMIT_HEADER_2                              0x3B//00h
#define RFM22B_REGISTER_3C_TRANSMIT_HEADER_1                              0x3C//00h
#define RFM22B_REGISTER_3D_TRANSMIT_HEADER_0                              0x3D//00h
#define RFM22B_REGISTER_3E_TRANSMIT_PACKET_LENGTH                         0x3E//00h
#define RFM22B_REGISTER_3F_CHECK_HEADER_3                                 0x3F//00h
#define RFM22B_REGISTER_40_CHECK_HEADER_2                                 0x40//00h
#define RFM22B_REGISTER_41_CHECK_HEADER_1                                 0x41//00h
#define RFM22B_REGISTER_42_CHECK_HEADER_0                                 0x42//00h
#define RFM22B_REGISTER_43_HEADER_ENABLE_3                                0x43//FFh
#define RFM22B_REGISTER_44_HEADER_ENABLE_2                                0x44//FFh
#define RFM22B_REGISTER_45_HEADER_ENABLE_1                                0x45//FFh
#define RFM22B_REGISTER_46_HEADER_ENABLE_0                                0x46//FFh
#define RFM22B_REGISTER_47_RECEIVED_HEADER_3                              0x47//-
#define RFM22B_REGISTER_48_RECEIVED_HEADER_2                              0x48//-
#define RFM22B_REGISTER_49_RECEIVED_HEADER_1                              0x49//-
#define RFM22B_REGISTER_4A_RECEIVED_HEADER_0                              0x4A//-
#define RFM22B_REGISTER_4B_RECEIVER_PACKET_LENGTH                         0x4B//-
//#define RFM22B_REGISTER_RESERVED                                        0x4C-0x4E
#define RFM22B_REGISTER_4F_ADC_8_CONTROL                                  0x4F//10h
//#define RFM22B_REGISTER_RESERVED                                        0x50-0x5F
#define RFM22B_REGISTER_60_CHANNEL_FILTER_COEFFICIENT_ADDRESS             0x60//00h
//#define RFM22B_REGISTER_RESERVED                                        0x61
#define RFM22B_REGISTER_62_CRYSTAL_OSCILLATOR_CONTROL_TEST                0x62//24h
//#define RFM22B_REGISTER_RESERVED                                        0x63-0x68
#define RFM22B_REGISTER_69_AGC_OVERRIDE                                   0x69//20h
//#define RFM22B_REGISTER_RESERVED                                        0x6A-0x6C
#define RFM22B_REGISTER_6D_TX_POWER                                       0x6D//18h
#define RFM22B_REGISTER_6E_TX_DATA_RATE_1                                 0x6E//0Ah
#define RFM22B_REGISTER_6F_TX_DATA_RATE_0                                 0x6F//3Dh
#define RFM22B_REGISTER_70_MODULATION_MODE_CONTROL_1                      0x70//0Ch
#define RFM22B_REGISTER_71_MODULATION_MODE_CONTROL_2                      0x71//00h
#define RFM22B_REGISTER_72_FREQUENCY_DEVIATION                            0x72//20h
#define RFM22B_REGISTER_73_FREQUENCY_OFFSET_1                             0x73//00h
#define RFM22B_REGISTER_74_FREQUENCY_OFFSET_2                             0x74//00h
#define RFM22B_REGISTER_75_FREQUENCY_BAND_SELECT                          0x75//75h
#define RFM22B_REGISTER_76_NOMINAL_CARRIER_FREQUENCY_1                    0x76//BBh
#define RFM22B_REGISTER_77_NOMINAL_CARRIER_FREQUENCY_0                    0x77//80h
//#define RFM22B_REGISTER_RESERVED                                        0x78
#define RFM22B_REGISTER_79_FREQUENCY_HOPPING_CHANNEL_SELECT               0x79//00h
#define RFM22B_REGISTER_7A_FREQUENCY_HOPPING_STEP_SIZE                    0x7A//00h
//#define RFM22B_REGISTER_RESERVED                                        0x7B
#define RFM22B_REGISTER_7C_TX_FIFO_CONTROL_1                              0x7C//37h
#define RFM22B_REGISTER_7D_TX_FIFO_CONTROL_2                              0x7D//04h
#define RFM22B_REGISTER_7E_RX_FIFO_CONTROL                                0x7E//37h
#define RFM22B_REGISTER_7F_FIFO_ACCESS                                      0x7F//-


#define RFM22B_LNA_SW                                                       1<<3

#define RFM22B_MC_CLK_30MHZ                                                 0b000
#define RFM22B_MC_CLK_15MHZ                                                 0b001
#define RFM22B_MC_CLK_10MHZ                                                 0b010
#define RFM22B_MC_CLK_4MHZ                                                  0b011
#define RFM22B_MC_CLK_3MHZ                                                  0b100
#define RFM22B_MC_CLK_2MHZ                                                  0b101
#define RFM22B_MC_CLK_1MHZ                                                  0b110
#define RFM22B_MC_CLK_32768HZ                                               0b111

#define RFM22B_STATUS_IDLE                                                  0b00
#define RFM22B_STATUS_RX                                                    0b01
#define RFM22B_STATUS_TX                                                    0b10
#define RFM22B_STATUS_FREQUENCY_ERROR                                       1<<3
#define RFM22B_STATUS_HEADER_ERROR                                          1<<4
#define RFM22B_STATUS_RX_FIFO_EMPTY                                         1<<5
#define RFM22B_STATUS_RX_TX_FIFO_UNDERFLOW                                  1<<6
#define RFM22B_STATUS_TX_TX_FIFO_OVERFLOW                                   1<<7
