#pragma once
#define   DEF_BYTE_ORDER_UNKNOWN        0
#define   DEF_BYTE_ORDER_LITTLE_ENDIAN  1
#define   DEF_BYTE_ORDER_BIG_ENDIAN     2


enum BYTE_ORDER
  {
  BYTE_ORDER_UNKNOWN        = DEF_BYTE_ORDER_UNKNOWN,
  BYTE_ORDER_LITTLE_ENDIAN  = DEF_BYTE_ORDER_LITTLE_ENDIAN,
  BYTE_ORDER_BIG_ENDIAN     = DEF_BYTE_ORDER_BIG_ENDIAN,
  };