#ifndef PROTOCOL_COMPUTER_HACK_H
#define PROTOCOL_COMPUTER_HACK_H

enum PROTO_HACK
	{
	PROTO_HACK_IS_HEAD,
	PROTO_HACK_COMMAND,
	PROTO_HACK_DATA_H,
	PROTO_HACK_DATA_L,
	PROTO_HACK_CRC16_H,
	PROTO_HACK_CRC16_L,
	PROTO_HACK_SIZE,
	};
/*enum HACK_HEADS
	{
	HACK_HEAD_PDA_TO_COMPUTER,
	HACK_HEAD_COMPUTER_TO_PDA,
	};*/

enum HACK_COMMANDS
	{
	HACK_COMMAND_GET_STATUS,
	HACK_COMMAND_TRY_TO_HACK,
	HACK_COMMAND_ANSWER_SUCCESS,
	HACK_COMMAND_M25P05_INSTRUCTION_READ_DATA_BYTES,
	HACK_COMMAND_ANSWER_FAILED,
	HACK_COMMAND_TOGGLE_SWITCH,
	};
enum COMPUTER_STATUSES
	{
	COMPUTER_STATUS_HACKED,
	COMPUTER_STATUS_SWITCH_ON,
	};
enum HACK_RESULT
	{
	HACK_RESULT_FAILED,
	HACK_RESULT_SUCCESS
	};
#endif